name: niranjan oranize CI

on:
  push:
    branches: [ $default-branch ]
  pull_requests: 
    branches: [ $default-branch ]


jobs:
  starter:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v3

      - name: run on one-line script
        run: Hello from Niru Organization
        
